# -*- coding: utf-8 -*-
""".gitignore

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SsH_-tzPsCDtn2QZzHDrsMOo7uSbQODj
"""

.ipynb_checkpoints
*/.ipynb_checkpoints/*